### PR TITLE
Deadline -- Support for timeouts during computation.

### PR DESCRIPTION
**Pull request by sshirokov**
This adds timing around sections of processing without any event calls so that if a timeout is detected the computation can be aborted early with an exception.

This is implemented with an `options` parameter to the `ThreeBSP` constructor which takes a `timeout` options in milliseconds.

This is the maximum amount of time that an operation can be performed in a blocking manner including new node construction, cloning operations and the `subtract` `union` `intersect` and `toMesh` methods.

### CODE REVIEW

**Comment by sshirokov** [comment]
Hm. I can add a progress callback for task completion.

**Comment by skalnik** [comment]
There's a bunch of `console.log` statements in here. Are those supposed to be kept around?

**Comment by sshirokov** [comment]
They should only be in `demo.js` to **SHOWCASE** the progress callback. Did you see something elsewhere?

**Comment by skalnik** [comment]
Ah yeah you're right. Just saw them pop up as I was `git add -p`ing the updated version. :+1:

**Pull request merged**
